language: groovy
script: ./gradlew clean build  -PbintrayUserName= -PbintrayApiKey --info
jdk:
 - oraclejdk7
 - oraclejdk8
 - openjdk7
 - openjdk6
 - openjdk8
os:
 - linux
 - osx
env: TERM=dumb
#after_success: ./gradlew coveralls -PbintrayUser= -PbintrayApiKey
