version: "{branch} {build}"



build:
  verbosity: detailed

build_script:
  - gradlew.bat build --info

branches:
  only:
    - master
    - development

artifacts:
  - path: '**\build\reports\tests'
    name: 'JUnit'