version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - gradlew.bat build --info

branches:
  only:
    - master
    - development

on_finish:
  - ps: $wc = New-Object 'System.Net.WebClient'
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\cloud-provider-core\build\test-results\TEST-org.ysb33r.groovy.vfsplugin.cloud.s3.S3Spec.xml))
