version: 1.0.{build}

build:
  verbosity: detailed

build_script:
  - gradlew.bat build

branches:
  only:
    - master
    - development

artifacts:
  - path: groovy-vfs\cloud-provider-core\build\reports\tests  
    name: Cloud-provider-core
